package com.cemcakmak.hydrotracker.ui.theme

import androidx.compose.ui.graphics.Color

// HydroTracker Tonal Palette based on #169181 (Teal Theme)
// Exported from Material Theme Builder; used as the fallback on devices without dynamic colour support.

// LIGHT THEME COLOR SCHEME
val md_theme_light_primary = Color(0xFF006B5E)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF9FF2E2)
val md_theme_light_onPrimaryContainer = Color(0xFF005047)
val md_theme_light_secondary = Color(0xFF4A635E)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFCDE8E1)
val md_theme_light_onSecondaryContainer = Color(0xFF334B46)
val md_theme_light_tertiary = Color(0xFF446179)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFCAE6FF)
val md_theme_light_onTertiaryContainer = Color(0xFF2C4A60)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF93000A)
val md_theme_light_background = Color(0xFFF4FBF8)
val md_theme_light_onBackground = Color(0xFF171D1B)
val md_theme_light_surface = Color(0xFFF4FBF8)
val md_theme_light_onSurface = Color(0xFF171D1B)
val md_theme_light_surfaceVariant = Color(0xFFDAE5E1)
val md_theme_light_onSurfaceVariant = Color(0xFF3F4946)
val md_theme_light_outline = Color(0xFF6F7976)
val md_theme_light_outlineVariant = Color(0xFFBEC9C5)
val md_theme_light_scrim = Color(0xFF000000)
val md_theme_light_inverseSurface = Color(0xFF2B3230)
val md_theme_light_inverseOnSurface = Color(0xFFECF2EF)
val md_theme_light_inversePrimary = Color(0xFF83D5C6)
val md_theme_light_surfaceTint = Color(0xFF006B5E)
val md_theme_light_primaryFixed = Color(0xFF9FF2E2)
val md_theme_light_onPrimaryFixed = Color(0xFF00201B)
val md_theme_light_primaryFixedDim = Color(0xFF83D5C6)
val md_theme_light_onPrimaryFixedVariant = Color(0xFF005047)
val md_theme_light_secondaryFixed = Color(0xFFCDE8E1)
val md_theme_light_onSecondaryFixed = Color(0xFF06201B)
val md_theme_light_secondaryFixedDim = Color(0xFFB1CCC5)
val md_theme_light_onSecondaryFixedVariant = Color(0xFF334B46)
val md_theme_light_tertiaryFixed = Color(0xFFCAE6FF)
val md_theme_light_onTertiaryFixed = Color(0xFF001E30)
val md_theme_light_tertiaryFixedDim = Color(0xFFACCAE5)
val md_theme_light_onTertiaryFixedVariant = Color(0xFF2C4A60)
val md_theme_light_surfaceDim = Color(0xFFD5DBD9)
val md_theme_light_surfaceBright = Color(0xFFF4FBF8)
val md_theme_light_surfaceContainerLowest = Color(0xFFFFFFFF)
val md_theme_light_surfaceContainerLow = Color(0xFFEFF5F2)
val md_theme_light_surfaceContainer = Color(0xFFE9EFEC)
val md_theme_light_surfaceContainerHigh = Color(0xFFE3EAE7)
val md_theme_light_surfaceContainerHighest = Color(0xFFDDE4E1)

// DARK THEME COLOR SCHEME
val md_theme_dark_primary = Color(0xFF83D5C6)
val md_theme_dark_onPrimary = Color(0xFF003730)
val md_theme_dark_primaryContainer = Color(0xFF005047)
val md_theme_dark_onPrimaryContainer = Color(0xFF9FF2E2)
val md_theme_dark_secondary = Color(0xFFB1CCC5)
val md_theme_dark_onSecondary = Color(0xFF1C3530)
val md_theme_dark_secondaryContainer = Color(0xFF334B46)
val md_theme_dark_onSecondaryContainer = Color(0xFFCDE8E1)
val md_theme_dark_tertiary = Color(0xFFACCAE5)
val md_theme_dark_onTertiary = Color(0xFF133348)
val md_theme_dark_tertiaryContainer = Color(0xFF2C4A60)
val md_theme_dark_onTertiaryContainer = Color(0xFFCAE6FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF0E1513)
val md_theme_dark_onBackground = Color(0xFFDDE4E1)
val md_theme_dark_surface = Color(0xFF0E1513)
val md_theme_dark_onSurface = Color(0xFFDDE4E1)
val md_theme_dark_surfaceVariant = Color(0xFF3F4946)
val md_theme_dark_onSurfaceVariant = Color(0xFFBEC9C5)
val md_theme_dark_outline = Color(0xFF899390)
val md_theme_dark_outlineVariant = Color(0xFF3F4946)
val md_theme_dark_scrim = Color(0xFF000000)
val md_theme_dark_inverseSurface = Color(0xFFDDE4E1)
val md_theme_dark_inverseOnSurface = Color(0xFF2B3230)
val md_theme_dark_inversePrimary = Color(0xFF006B5E)
val md_theme_dark_surfaceTint = Color(0xFF83D5C6)
val md_theme_dark_primaryFixed = Color(0xFF9FF2E2)
val md_theme_dark_onPrimaryFixed = Color(0xFF00201B)
val md_theme_dark_primaryFixedDim = Color(0xFF83D5C6)
val md_theme_dark_onPrimaryFixedVariant = Color(0xFF005047)
val md_theme_dark_secondaryFixed = Color(0xFFCDE8E1)
val md_theme_dark_onSecondaryFixed = Color(0xFF06201B)
val md_theme_dark_secondaryFixedDim = Color(0xFFB1CCC5)
val md_theme_dark_onSecondaryFixedVariant = Color(0xFF334B46)
val md_theme_dark_tertiaryFixed = Color(0xFFCAE6FF)
val md_theme_dark_onTertiaryFixed = Color(0xFF001E30)
val md_theme_dark_tertiaryFixedDim = Color(0xFFACCAE5)
val md_theme_dark_onTertiaryFixedVariant = Color(0xFF2C4A60)
val md_theme_dark_surfaceDim = Color(0xFF0E1513)
val md_theme_dark_surfaceBright = Color(0xFF343B39)
val md_theme_dark_surfaceContainerLowest = Color(0xFF090F0E)
val md_theme_dark_surfaceContainerLow = Color(0xFF171D1B)
val md_theme_dark_surfaceContainer = Color(0xFF1B211F)
val md_theme_dark_surfaceContainerHigh = Color(0xFF252B2A)
val md_theme_dark_surfaceContainerHighest = Color(0xFF303634)
